### ISSUE TITLE
process.env.NODE_ENV is undefined in tests

### ISSUE THREAD

**Issue by joshwcomeau** [insin/nwb#156]
Hello there!

I'm running a `web_module` with `nwb` 0.11, node 6.2.2.

I'm trying to write test-only code, using `process.env.NODE_ENV`, and it's coming up undefined.

Even when I prefix the NPM script (`NODE_ENV=test nwb test`), it remains undefined inside the tests. In fact, `process.env` is an empty object, without any of my normal environment variables.

How can I populate NODE_ENV in tests?

**Comment by insin** [comment]
Webpack *should* be replacing any `process.env.NODE_ENV` expressions in your code with "test", as:
- [`NODE_ENV` is forced to `test` during test runs](https://github.com/insin/nwb/blob/9d9e8861c2e25c5938fc0aaf739eac6cb23a9e88/src/commands/test.js#L9)
- [The  current value of `NODE_ENV` is injected with `DefinePlugin`](https://github.com/insin/nwb/blob/9d9e8861c2e25c5938fc0aaf739eac6cb23a9e88/src/createWebpackConfig.js#L265)

This will only work if your code uses the literal expression `process.env.NODE_ENV`, not if it does something like pulling out `process.env` into a variable and trying to access `NODE_ENV` from that.

You won't see any of your Node.js environment variables in `process` because your tests are being bundled up by Webpack and run in a browser. If you have any `process` references hanging around after `process.env.NODE_ENV` is replaced, Webpack will actually inject a shim for `process` from [node-libs-browser](https://github.com/webpack/node-libs-browser).

Do you have some example code I could use to try to replicate this if none of the above helps? :smile_cat:

**Comment by joshwcomeau** [comment]
First, thanks so much for the quick and detailed reply =).

Bewilderingly, it works just fine today. I must've been doing something wrong; I forgot about how `definePlugin` replaces the term itself, so it makes total sense that other environment variables don't exist.

Appreciate the support! Closing the issue.
