### ISSUE TITLE
Add preact support

### ISSUE THREAD

**Issue by insin** [insin/nwb#166]
- `nwb new preact-app <name>`
- `nwb build-preact-app`
- `nwb serve-preact-app` - with the necessary hot reloading code in the app skeleton

Preact's tiny size makes it really compelling for Progressive Web App usage, so how about investigating [sw-precache-webpack-plugin](https://github.com/goldhand/sw-precache-webpack-plugin) with a view to adding `nwb new preact-pwa <name>`? [react-hn](https://github.com/insin/react-hn) could likely use whatever new config we have to provide/support, too.

**Comment by developit** [comment]
@insin ws-precache seems fitting here. I've been using OfflinePlugin, but I have been toying with switching to ws-precache since it's easier to extend via sw-toolbox.

Regarding your JSX pragma import question, I'm always happy to support either `import preact from 'preact'` and `import { h } from 'preact'`.  Personally I prefer the latter, since I tend to favor specific imports over property bag imports, but that's just my opinion 👍

**Comment by insin** [comment]
In any case, it will be... :sunglasses: configurable.

**Comment by insin** [comment]
Added in v0.13.0
