### ISSUE TITLE
Question: Why are dependencies not specified using semver ?

### ISSUE THREAD

**Issue by late-warrior** [insin/nwb#264]
This issue is a: 

- [ ] Bug report
- [ ] Feature request
- [x ] Question / support request
- [ ] Other

Why are all [dependencies](https://github.com/insin/nwb/blob/master/package.json) locked into a specific version and not using semver ? Is this because we want ``nwb`` to be 'predictable' ?  

BTW - thanks for nwb - it really helps newcomers be productive off the bat.  Your [reusable tooling](https://github.com/insin/ad-hoc-reckons/blob/master/CreatingReusableDevelopmentTooling.md) post was a great read too.

**Comment by insin** [comment]
It's done this way reduce the chances of the same version of nwb installed at different times getting broken or having its behaviour changed by changes in one of the development dependencies listed in its `dependencies`.

We're still at the mercy of transitive dependencies specified using a version range (which is still npm's default behaviour) publishing a broken version- e.g. a patch version change in `acorn` recently broke `webpack` and fixed it in another patch version soon after - but it's better than nothing.

Since nwb is a development dependency, it's ultimately up to users if they want to use npm shrinkwrap or yarn for reproducible builds though.

(Version ranges are an npm thing, though - [semver](http://semver.org/) doesn't specify them)
