### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by ashleygwilliams** [insin/nwb#29]
this project looks great, but the npm version is troublingly out of date. is there anything i can do to help you upgrade?

**Comment by insin** [comment]
Do you have any info on what usage is like for npm 2 vs 3? I'm assuming most people on Node.js < 5 will still be using the default npm 2 for a while, and intend to support both while there's still significant usage of npm 2.

I've already dealt with some 2 vs. 3 [local install issues](https://github.com/insin/nwb/issues/1), though it's been a while since I last tested with npm 3, so I guess I need to start by adding Node.js 5 to the CI builds first.

Is there anything else you commonly encounter helping people upgrade?

**Comment by insin** [comment]
A Node 5 / npm3 build is now running on Travis
