### ISSUE TITLE
React component UMD build fails at runtime

### ISSUE THREAD

**Issue by coryhouse** [insin/nwb#402]
This issue is a: Bug report

The latest version of nwb's React UMD build fails at runtime. 

# REPRO REPOS
1. [Repo where I created my-component and generated a React component UMD build](https://github.com/coryhouse/my-component)
2. [Repo that consumes the component above](https://github.com/coryhouse/react-umd-example). Run this and you'll see the UMD build fails at runtime. 

I have a separate repo that works fine with nwb 0.11.0, so this appears to be a regression in nwb.

Which versions of Node.js, npm and nwb are you using (if using it globally)?

```
node -v 8.9.1
npm -v 5.5.1
# If nwb is being used as a global install
nwb -v 0.19.2
```

Which modules are installed in your project?

```
npm ls --depth=0
```

Try setting the `DEBUG` environment variable to `nwb` before running to check what generated configuration looks like:

```
# *nix
export DEBUG=nwb
# Windows
set DEBUG=nwb
```

**Comment by insin** [comment]
It looks like it's now exporting an ES6 interop-style module instead of exporting `MyComponent` directly, as it works if I change it to `React.createElement(MyComponent.default)`.

I don't think the [webpack config for this](https://github.com/insin/nwb/blob/4ca2d46ecba1c4def51d4afd71265383a10052b7/src/moduleBuild.js#L71-L85) was changed when upgrading to Webpack 2 and beyond, so will look into what changes are needed.

I've also been considering switching to Rollup for component UMD builds (#316 ) so this might be a good opportunity to investigate properly.

Thanks for the repro repos, made this so easy to investigate!

**Comment by insin** [comment]
Looks like we need to add `libraryExport: 'default'` to the config: https://github.com/webpack/webpack/issues/3929

**Comment by coryhouse** [comment]
Ah! Easy change. :) Thanks for the quick reply! 🎉

**Comment by hboylan** [comment]
Great find. I've just run into this issue as well with `nwb@0.20.0`.

Is it possible to add the setting to my own `nwb.config.js` for now?
