### ISSUE TITLE
Is it possible to add a WebPack plugin in nwb.config.js?

### ISSUE THREAD

**Issue by stevesouth** [insin/nwb#43]
I can't see how at first glance.

To be clear about my underlying requirement I am trying to add a custom resolver as per.

http://stackoverflow.com/questions/28026428/is-it-possible-to-create-custom-resolver-in-webpack

**Comment by insin** [comment]
it's [not possible at the moment](https://github.com/insin/nwb/blob/ba2f77e42be59b559a50453096aa9342283018e6/docs/Introduction.md#not-configurable-yet) because I wasn't sure how to expose tweaking of the plugins nwb manages to the user, but adding support for providing extra plugins might not take much effort.

nwb would need to pass its version of webpack to your config, so how does the following look as a speculative `nwb.config.js` config API?

```js
var MyConventionResolver = {
  // ...
}

module.exports = function(deps) {
  return {
    type: 'react-app',
    plugins: {
      extra: [
        new deps.webpack.ResolverPlugin([MyConventionResolver])
      ]
    }
  }
}
````

**Comment by stevesouth** [comment]
Looks fine, although why don't you have.

**Comment by insin** [comment]
I was trying to reduce the amount of nesting needed for config when there wasn't as much of it , probably over-influenced by writing the [initial documentation](https://github.com/insin/nwb/blob/ba2f77e42be59b559a50453096aa9342283018e6/docs/Configuration.md#webpack-configuration) with code examples code per config item.

It does need to be made more consistent, along the lined of Karma config, which all lives under a `kaema` prop.
