### ISSUE TITLE
0.8 release has issue with Symbols

### ISSUE THREAD

**Issue by vitkon** [insin/nwb#70]
`nwb test` returns `Can't find variable: Symbol` for some scenarios

looks similar to this issue
https://til.hashrocket.com/posts/b4c0e5d1a4-cant-find-variable-symbol

What's the best way to fix it?

**Comment by insin** [comment]
Hmm, that might be caused by this change. I removed the Babel polyfill as I was only intending to use it to patch `Function.prototype.bind()` for PhantomJS 1.x:

https://github.com/insin/nwb/commit/d9677e39f7468e99e55e29ae420fcb183c512638#diff-12a91575bde19ee7675c83307d7357e8L132

Do you have something I can reproduce the error with?

**Comment by vitkon** [comment]
this bit of code caused and issue:

`
export function hasChild(child, component) {
	const newChildren = React.Children.toArray(child);

	for (const newchild of newChildren) {
		if (newchild.type && newchild.type === component) {
			return true;
		} else if (component === typeof newchild) {
			return true;
		}
	}
	return false;
}
`

I refactored it a bit and the issue was gone, hence I close the issue.
