### ISSUE TITLE
"version": "0.0.0"?

### ISSUE THREAD

**Issue by tomByrer** [insin/nwb#96]
I'd prefer to start a new project at a 0 version.  But they seem to be hardwired at [v1.0.0](https://github.com/insin/nwb/blob/master/templates/react-app/_package.json#L3).  Even [your own project](https://github.com/insin/nwb/blob/master/package.json#L4) hasn't hit v1.0.0 yet!
Let me know if you'd like a PR.

**Comment by slmgc** [comment]
@tomByrer, why it's a bad idea: http://www.jongleberry.com/semver-has-failed-us.html

**Comment by insin** [comment]
The `new` and `init` commands are there solely to provide a default "it'll do" workflow, so I'm not keen on adding more config around them unless it's essential - thanks for offering a PR, but no thanks on this particular change.

`nwb` uses `0.x.y` versioning [and defines its own semantics for what these versions mean](https://github.com/insin/nwb#versioning) because I don't think its API (in the form of `nwb.config.js`) can be considered stable until it moves to the current version of Babel - that might even involve dropping support for npm2, although I want to avoid that if possible :disappointed:
